[profile.default]
solc-version = "0.8.30"
runs = 10_000_000
via_ir = true
libs = ["node_modules", "lib"]

[profile.solx]
solc_version = "~/.local/bin/solx"

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
override_spacing = false
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"
